//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.2.1-SNAPSHOT
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from E:\EDGolog\LanguageRecognition\PlanningDomain.g4 by ANTLR 4.2.1-SNAPSHOT

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

namespace LanguageRecognition {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="PlanningDomainParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.2.1-SNAPSHOT")]
[System.CLSCompliant(false)]
public interface IPlanningDomainVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlanningDomainParser.structDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructDef([NotNull] PlanningDomainParser.StructDefContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PlanningDomainParser.listName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitListName([NotNull] PlanningDomainParser.ListNameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PlanningDomainParser.primType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimType([NotNull] PlanningDomainParser.PrimTypeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PlanningDomainParser.actBodyDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActBodyDef([NotNull] PlanningDomainParser.ActBodyDefContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PlanningDomainParser.atomicFormSke"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtomicFormSke([NotNull] PlanningDomainParser.AtomicFormSkeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PlanningDomainParser.gd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGd([NotNull] PlanningDomainParser.GdContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PlanningDomainParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] PlanningDomainParser.TypeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PlanningDomainParser.prefGD"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrefGD([NotNull] PlanningDomainParser.PrefGDContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PlanningDomainParser.reqDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReqDef([NotNull] PlanningDomainParser.ReqDefContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PlanningDomainParser.predDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPredDef([NotNull] PlanningDomainParser.PredDefContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PlanningDomainParser.listVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitListVar([NotNull] PlanningDomainParser.ListVarContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PlanningDomainParser.atomicForm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtomicForm([NotNull] PlanningDomainParser.AtomicFormContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PlanningDomainParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm([NotNull] PlanningDomainParser.TermContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PlanningDomainParser.actSym"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActSym([NotNull] PlanningDomainParser.ActSymContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PlanningDomainParser.funTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunTerm([NotNull] PlanningDomainParser.FunTermContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PlanningDomainParser.domain"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDomain([NotNull] PlanningDomainParser.DomainContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PlanningDomainParser.reqKey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReqKey([NotNull] PlanningDomainParser.ReqKeyContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PlanningDomainParser.typeDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeDef([NotNull] PlanningDomainParser.TypeDefContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PlanningDomainParser.pred"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPred([NotNull] PlanningDomainParser.PredContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PlanningDomainParser.prefName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrefName([NotNull] PlanningDomainParser.PrefNameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PlanningDomainParser.actDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActDef([NotNull] PlanningDomainParser.ActDefContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PlanningDomainParser.preGD"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPreGD([NotNull] PlanningDomainParser.PreGDContext context);
}
} // namespace LanguageRecognition
