copy "E:\EDGolog\SquirrelsWorlds\bin\Debug\*.exe" "%USERPROFILE%\Desktop\Server\"
copy "E:\EDGolog\SquirrelsWorlds\bin\Debug\*.dll" "%USERPROFILE%\Desktop\Server\"
copy "E:\EDGolog\SquirrelsWorlds\bin\Debug\*.pdb" "%USERPROFILE%\Desktop\Server\"
copy "E:\EDGolog\SquirrelsWorlds\bin\Debug\swServerProblem.pddl" "%USERPROFILE%\Desktop\Server\"
copy "E:\EDGolog\SquirrelsWorlds\bin\Debug\swDomain.pddl" "%USERPROFILE%\Desktop\Server\"