(define (problem sw-7-3)
	(:domain squirrelsWorlds)
	(:constants (maxLoc 7) (maxAcorn 3) (noticeRelLoc 1) (errorSencingAcorn 1))
	(:init 
		(loc a1 0)
		(loc a2 7)
		(acorn 0 2)
		(acorn 1 2)
		(acorn 2 2)
		(acorn 3 2)
		(acorn 4 2)
		(acorn 5 2)
		(acorn 6 2)
		(acorn 7 2)
    )
)