(define (problem sw-7-3)
	(:domain squirrelsWorlds)
	(:numbers (maxLoc 7) (maxAcorn 3) (noticeRelLoc 1) (errorSencingAcorn 1))
	(:init
		(loc a1 0)
		(loc a2 7)
		(acorn 0 1)
		(acorn 1 1)
		(acorn 2 1)
		(acorn 3 1)
		(acorn 4 1)
		(acorn 5 1)
		(acorn 6 1)
		(acorn 7 1)		
    )
)